import React, { useState, useMemo, useEffect } from 'react';
import { MapContainer, TileLayer, Marker, Popup, CircleMarker, Polyline } from 'react-leaflet';
import 'leaflet/dist/leaflet.css';
import L from 'leaflet';
// 1. Import useSearchParams
import { useSearchParams } from 'react-router-dom';
import { getDistance } from 'geolib';

// Import our components and data
import { warehouses, demandSignals, storeLocations } from '../utils/warehouseData.js';
import AutocompleteSearch from '../components/AutocompleteSearch.jsx';

// --- Icon Fix (Keep this) ---
import icon from 'leaflet/dist/images/marker-icon.png';
import iconShadow from 'leaflet/dist/images/marker-shadow.png';
let DefaultIcon = L.icon({
    iconUrl: icon,
    shadowUrl: iconShadow,
    iconAnchor: [12, 41]
});
L.Marker.prototype.options.icon = DefaultIcon;
// --- End of fix ---

// Helper function for marker colors
const getPriorityOptions = (priority) => {
  switch (priority) {
    case 1: return { color: '#ef4444', fillColor: '#fca5a5' }; // Red
    case 2: return { color: '#f59e0b', fillColor: '#fde68a' }; // Yellow
    case 3: return { color: '#22c55e', fillColor: '#bbf7d0' }; // Green
    default: return { color: '#818cf8', fillColor: '#c7d2fe' }; // Indigo (Warehouse)
  }
};

// Route line style
const routeLineOptions = { color: '#4f46e5', weight: 4, opacity: 0.7, dashArray: '5, 10' };


const LogisticsPage = () => {
  // Global map center
  const mapCenter = [20, 0];
  const mapZoom = 2;

  // State for selected locations
  const [startLoc, setStartLoc] = useState(null);
  const [endLoc, setEndLoc] = useState(null);
  
  // 2. Get URL search parameters
  const [searchParams] = useSearchParams();

  // 3. --- NEW: Check for URL params on load ---
  useEffect(() => {
    const startLat = searchParams.get('startLat');
    const startLng = searchParams.get('startLng');
    const endLat = searchParams.get('endLat');
    const endLng = searchParams.get('endLng');

    // If all params exist, set the route automatically
    if (startLat && startLng && endLat && endLng) {
      const startPos = [parseFloat(startLat), parseFloat(startLng)];
      const endPos = [parseFloat(endLat), parseFloat(endLng)];
      
      // Find the names from our data files
      const startName = warehouses.find(w => w.pos[0] === startPos[0])?.city || 'Selected Warehouse';
      const endName = storeLocations['S001']?.city || 'Destination Store'; // Assuming S001 for demo

      setStartLoc({ pos: startPos, city: startName });
      setEndLoc({ pos: endPos, city: endName });
    }
  }, [searchParams]); // Rerun if params change

  // 4. Calculate distance (this logic is unchanged)
  const { routeLine, distanceKm } = useMemo(() => {
    if (!startLoc || !endLoc) {
      return { routeLine: [], distanceKm: 0 };
    }
    const line = [startLoc.pos, endLoc.pos];
    const distanceMeters = getDistance(
      { latitude: startLoc.pos[0], longitude: startLoc.pos[1] },
      { latitude: endLoc.pos[0], longitude: endLoc.pos[1] }
    );
    const distanceKm = (distanceMeters / 1000).toFixed(0);
    return { routeLine: line, distanceKm };
  }, [startLoc, endLoc]);

  // 5. Check if a route was passed via URL
  const isRoutePreloaded = !!searchParams.get('startLat');

  return (
    <div className="space-y-6">
      <div className="bg-white p-6 rounded-xl shadow-lg border border-gray-100">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">
          Global Logistics & Distribution
        </h2>

        {/* --- 6. Show Search or just Results --- */}
        <div className={`grid grid-cols-1 md:grid-cols-3 gap-6 mb-4 p-4 bg-gray-50 rounded-lg items-center`}>
          {/* Hide search boxes if a route is preloaded */}
          {!isRoutePreloaded ? (
            <>
              <AutocompleteSearch 
                items={warehouses}
                onSelect={(item) => setStartLoc(item)}
                placeholder="Start (Warehouse)"
              />
              <AutocompleteSearch 
                items={demandSignals}
                onSelect={(item) => setEndLoc(item)}
                placeholder="Destination (Demand Signal)"
              />
            </>
          ) : (
             <div className="md:col-span-2">
                <h3 className="text-lg font-semibold text-indigo-600">Displaying AI-Recommended Route</h3>
                <p className="text-sm text-gray-600">This route was generated by the AI Decision Model.</p>
             </div>
          )}
          
          {/* Results Box (always show) */}
          <div className={`bg-white p-4 rounded-lg shadow h-full ${isRoutePreloaded ? 'md:col-span-1' : ''}`}>
            <h4 className="text-sm font-medium text-gray-500">Route Details</h4>
            {distanceKm > 0 ? (
              <>
                <p className="text-2xl font-bold text-indigo-600">
                  {Number(distanceKm).toLocaleString('en-IN')} km
                </p>
                <p className="text-xs text-gray-500">
                  From: {startLoc.city}
                  <br/>
                  To: {endLoc.city}
                </p>
              </>
            ) : (
              <p className="text-gray-500 text-sm pt-2">Please select a start and end point.</p>
            )}
          </div>
        </div>
        
        {/* Map container */}
        <div style={{ height: '600px', width: '100%' }} className="rounded-lg overflow-hidden">
          <MapContainer 
            center={mapCenter} 
            zoom={mapZoom} 
            style={{ height: '100%', width: '100%' }}
          >
            {/* Light theme map */}
            <TileLayer
              url="https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png"
              attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors &copy; <a href="https://carto.com/attributions">CARTO</a>'
            />
            
            {/* Render Warehouse Nodes */}
            {warehouses.map(wh => (
              <CircleMarker
                key={wh.id}
                center={wh.pos}
                radius={8}
                pathOptions={getPriorityOptions(null)}
              >
                <Popup><strong>{wh.name}</strong><br/>{wh.city}</Popup>
              </CircleMarker>
            ))}

            {/* Render Demand Nodes */}
            {demandSignals.map(zone => (
              <CircleMarker
                key={zone.id}
                center={zone.pos}
                radius={8}
                pathOptions={getPriorityOptions(zone.priority)}
              >
                <Popup>
                  <strong style={{color: getPriorityOptions(zone.priority).color}}>
                    {zone.priority === 1 ? 'URGENT: ' : ''}{zone.name}
                  </strong>
                  <br/>{zone.city}
                </Popup>
              </CircleMarker>
            ))}

            {/* Render Route Line */}
            {routeLine.length > 0 && (
              <Polyline pathOptions={routeLineOptions} positions={routeLine} />
            )}
          </MapContainer>
        </div>
      </div>
    </div>
  );
};

export default LogisticsPage;